#!/bin/bash
# @File: start-jupyter-notenook-service
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-02

docker run -d --name jupyter-notebook-service \
-e TZ=Asia/Shanghai \
-p 51002:8888 \
-v /data/container/volume/jupyter-notebok/work:/home/jovyan/work \
jupyter/base-notebook:latest
